// Example: Add this array to your component or a separate file
const funnyQuotes = [
  "I'm not arguing, I'm just explaining why I'm right.",
  "I used to think I was indecisive, but now I'm not so sure.",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why don’t scientists trust atoms? Because they make up everything!",
  "I told my computer I needed a break, and it said 'No problem, I'll go to sleep.'",
  "I’m not lazy, I’m on energy-saving mode.",
  "If at first you don’t succeed, then skydiving definitely isn’t for you.",
  "Life is short. Smile while you still have teeth.",
  "My bed is a magical place where I suddenly remember everything I forgot to do.",
  "I’m not great at the advice. Can I interest you in a sarcastic comment?",
  "I put my phone in airplane mode, but it’s not flying!",
  "I’m not arguing, I’m just passionately expressing my point of view.",
  "I’m not weird, I’m limited edition.",
  "I’m not lazy, I just rest before I get tired.",
  "If you think nobody cares if you’re alive, try missing a couple of payments.",
  "I’m not short, I’m concentrated awesome.",
  "I’m not running late. I’m fashionably delayed.",
  "I’m not procrastinating. I’m doing side quests.",
  "I’m not clumsy, it’s just the floor hates me, the tables and chairs are bullies, and the walls get in my way.",
  "I’m not arguing, I’m just explaining why I’m right.",
  "I’m not a complete idiot. Some parts are missing.",
  "I’m not lazy, I’m just very relaxed.",
  "I’m not ignoring you, I’m just giving you time to reflect on what you just said.",
  "I’m not bossy, I just have better ideas.",
  "I’m not old, I’m 25 plus shipping and handling.",
  "I’m not a morning person. Don’t pull the covers off.",
  "I’m not addicted to coffee, we’re just in a committed relationship.",
  "I’m not sure how many problems I have because math is one of them.",
  "I’m not arguing, I’m just explaining why I’m right.",
  "I’m not lazy, I’m just on my energy-saving mode.",
  "I’m not late, I’m just early for tomorrow.",
  "I’m not a complete idiot, some parts are missing.",
  "I’m not arguing, I’m just explaining why I’m right.",
  "I’m not lazy, I’m just on my energy-saving mode.",
  "I’m not arguing, I’m just explaining why I’m right.",
  "I’m not lazy, I’m just on my energy-saving mode.",
  "I’m not arguing, I’m just explaining why I’m right.",
  "I’m not lazy, I’m just on my energy-saving mode.",
  "I’m not arguing, I’m just explaining why I’m right.",
  "I’m not lazy, I’m just on my energy-saving mode.",
  "I’m not arguing, I’m just explaining why I’m right.",
  "I’m not lazy, I’m just on my energy-saving mode.",
  "I’m not arguing, I’m just explaining why I’m right.",
  "I’m not lazy, I’m just on my energy-saving mode.",
  "I’m not arguing, I’m just explaining why I’m right.",
  "I’m not lazy, I’m just on my energy-saving mode.",
  "I’m not arguing, I’m just explaining why I’m right.",
  "I’m not lazy, I’m just on my energy-saving mode.",
  "I’m not arguing, I’m just explaining why I’m right.",
  "I’m not lazy, I’m just on my energy-saving mode."
];

export default funnyQuotes;