const loveQuotes = [
  "You are my today and all of my tomorrows.",
  "Every love story is beautiful, but ours is my favorite.",
  "I love you more than coffee, but please don’t make me prove it.",
  "You make my heart smile.",
  "With you, every moment is sweet.",
  "You’re the peanut butter to my jelly.",
  "I still fall for you every single day.",
  "You’re my favorite notification.",
  "If kisses were snowflakes, I’d send you a blizzard.",
  "You’re the reason I look down at my phone and smile.",
  "I love you to the moon and back, and then some.",
  "You’re my sunshine on a cloudy day.",
  "I’d choose you in every lifetime.",
  "You’re the missing piece to my puzzle.",
  "You’re my happily ever after.",
  "You’re the sprinkles on my ice cream.",
  "I love you more than pizza. And that’s saying a lot.",
  "You’re my favorite hello and my hardest goodbye.",
  "You’re the cheese to my macaroni.",
  "You’re the reason my heart beats a little faster.",
  "You’re my cuddle buddy for life.",
  "You’re the marshmallow to my hot chocolate.",
  "You’re the smile I wear every day.",
  "You’re the apple of my pie.",
  "You’re my sweetest adventure.",
  "You’re the syrup to my pancakes.",
  "You’re the sparkle in my eyes.",
  "You’re my home and my heart.",
  "You’re the jelly to my donut.",
  "You’re the dream I never want to wake up from.",
  "You’re my favorite place to be.",
  "You’re the honey to my tea.",
  "You’re the reason I believe in love.",
  "You’re my heart’s favorite song.",
  "You’re the cherry on top of my life.",
  "You’re my forever and always.",
  "You’re the magic in my ordinary days.",
  "You’re my favorite person to do nothing with.",
  "You’re the reason I smile for no reason.",
  "You’re my love at first sight and every sight after.",
  "You’re the best part of my day.",
  "You’re the rainbow after my rain.",
  "You’re my snuggle bug.",
  "You’re the reason my heart does a happy dance.",
  "You’re my sweetest daydream.",
  "You’re the light that guides me home.",
  "You’re my favorite chapter in my story.",
  "You’re the reason I believe in fairy tales.",
  "You’re my heart’s happy place.",
  "You’re the love I never knew I needed."
];

export default loveQuotes;